### PR TITLE
Richesh27 facebook login clone using tailwind 162

### PR DESCRIPTION
**Pull request by richesh27**
**Issue reference:**
issue number #162 
**Proposed changes:**
added facebook clone
**Type of change:**
added a new project
Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Other (please specify)

**Checklist:**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

**Additional info (if any):**

### CODE REVIEW

**Comment by richesh27** [comment]
Kindly check it out.

**Review by RajVarsani — COMMENTED** [review]
Nice work @richesh27 
Please remove `node_modules` and add it in `.gitignore` file.

**Comment by richesh27** [comment]
I've made the necessary required changes. Kindly review it

**Review by RajVarsani — APPROVED** [review]
LGTM. Great work @richesh27

**Pull request merged**
