### PR TITLE
added car game 

### PR DESCRIPTION
**Pull request by YugalPradhan**
please add hacktoberfest and hacktoberfest accepted tag and merge my pull request

### CODE REVIEW

**Review by RajVarsani — CHANGES_REQUESTED** [review]
Excellent work, @YugalPradhan, just a small change. Please move this project inside the `projects/` directory.

**Comment by RajVarsani** [comment]
Please reference the related issue(#149) in the PR too.

**Comment by YugalPradhan** [comment]
changes applied,
issue resolved-
#149

**Review by RajVarsani — CHANGES_REQUESTED** [review]
Nice @YugalPradhan . I can't find `index.html` in this folder, can you update the folder structure accordingly?

**Review by RajVarsani — APPROVED** [review]
LGTM. great work @YugalPradhan

**Pull request merged**
