### PR TITLE
Added: Project of basketball scoreboard

### PR DESCRIPTION
**Pull request by LitPreet**
Hey there!
I have completed this project of basketball scoreboard.
using tailwind css and javascript.

this is my first hactoberfest 20

https://user-images.githubusercontent.com/77205201/195375240-dad56b46-474a-46e4-bf98-3e03a9243224.mp4

22 .
plz merge this project in main directory.
Happy Coding😎😍

### CODE REVIEW

**Review by RajVarsani — CHANGES_REQUESTED** [review]
Nice work @LitPreet 
please remove node modules.

Happy Hacking 😎

**Comment by LitPreet** [comment]
Now I have removed node modules as you said.
kindly merge this pull request

**Review by LitPreet — COMMENTED** [review]
I have removed the node modules as you said
now kindly merge ,my request.
Happy coding😍

**Comment by RajVarsani** [comment]
LGTM Sure 🙌

**Review by RajVarsani — APPROVED** [review]

**Pull request merged**
