### PR TITLE
CollegeGuide proj added

### PR DESCRIPTION
**Pull request by Nitya-Pasrija**
#89 

**Proposed changes:**
Have added the website project

**Type of change:**

Please delete options that are not relevant.

- [x] Other (added a new project)

**Checklist:**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

**Additional info (if any):**

### CODE REVIEW

**Comment by Nitya-Pasrija** [comment]
Ok damn, I figured adding x in the checkbox will make it a check, as this feature works in other Github repos. 
Kindly see to it that I wished to add a check and not a cross.. @RajVarsani 
Thanks :)

**Comment by RajVarsani** [comment]
Calm, no worries, @Nitya-Pasrija. You can easily edit it. Remove spaces and have Xs only inside the brackets; it will work.

**Comment by Nitya-Pasrija** [comment]
Yep, works now :)

**Review by RajVarsani — APPROVED** [review]
Nice work @Nitya-Pasrija 🔥

**Pull request merged**
